const acdemyDat = [
    {
     id:1,
     courseImage:"https://img.freepik.com/premium-photo/stewardess-with-crossed-arms-leaning-her-back-against-turbofan-engine_447912-3940.jpg?w=1380",   
     courseTitle:"Passenger Service Associate",
     aboutCourse:"A Passenger Service Associate (PSA) Academy program is a specialized training course created to equip individuals with the essential abilities and understanding necessary for roles in passenger services within the aviation sector. This curriculum addresses a broad spectrum of subjects linked to passenger handling",
     courseRating:4,
     totelRting:"1k + rating",
     totalHurs:"56 + total Hours ",
     Lectures:"67 + ",
     language:"Hindi",
     oldPrice:"32000",
     newPrice:"27500",
    },
        {
     id:2,
     courseImage:"https://res.cloudinary.com/dxgmovaih/image/upload/v1753359162/wmremove-transformed_3_mcds7m.jpg",   
     courseTitle:"Human Resource [HR]",
     aboutCourse:"A Passenger Service Associate (PSA) Academy program is a specialized training course created to equip individuals with the essential abilities and understanding necessary for roles in passenger services within the aviation sector. This curriculum addresses a broad spectrum of subjects linked to passenger handling",
     courseRating:4.9,
     totelRting:"12k + rating",
     totalHurs:"87 + total Hours ",
     Lectures:"80 + ",
     language:"Hindi",
     oldPrice:"31000",
     newPrice:"26500",
    },
        {
     id:3,
     courseImage:"https://res.cloudinary.com/dxgmovaih/image/upload/v1753359818/my-fashion-business-is-expanding-quickly-hispanic-business-owner-feeling-proud-her-startup-online-clothing-shop_662251-1974_evnpga.jpg",   
     courseTitle:"Sales And Retail Management",
     aboutCourse:"A Passenger Service Associate (PSA) Academy program is a specialized training course created to equip individuals with the essential abilities and understanding necessary for roles in passenger services within the aviation sector. This curriculum addresses a broad spectrum of subjects linked to passenger handling",
     courseRating:4,
     totelRting:"1k + rating",
     totalHurs:"56 + total Hours ",
     Lectures:"67 + ",
     language:"Hindi",
      oldPrice:"30000",
     newPrice:"25500",
    },
       {
     id:4,
     courseImage:"https://res.cloudinary.com/dxgmovaih/image/upload/v1753359662/young-lovely-couple-sitting-with-manager-travel-agency-office-prepairing-summer-vacation_506452-3189_ryxfdk.jpg",   
     courseTitle:"Travel And Tourism Management",
     aboutCourse:"A Passenger Service Associate (PSA) Academy program is a specialized training course created to equip individuals with the essential abilities and understanding necessary for roles in passenger services within the aviation sector. This curriculum addresses a broad spectrum of subjects linked to passenger handling",
     courseRating:4,
     totelRting:"1k + rating",
     totalHurs:"56 + total Hours ",
     Lectures:"67 + ",
     language:"Hindi",
      oldPrice:"32000",
     newPrice:"26500",
    },
       {
     id:5,
     courseImage:"https://res.cloudinary.com/dxgmovaih/image/upload/v1753360117/wmremove-transformed_4_iqkzjt.jpg",   
     courseTitle:"Project Management",
     aboutCourse:"A Passenger Service Associate (PSA) Academy program is a specialized training course created to equip individuals with the essential abilities and understanding necessary for roles in passenger services within the aviation sector. This curriculum addresses a broad spectrum of subjects linked to passenger handling",
     courseRating:4,
     totelRting:"1k + rating",
     totalHurs:"56 + total Hours ",
     Lectures:"67 + ",
     language:"Hindi",
    oldPrice:"33000",
     newPrice:"27500",
    },
       {
     id:6,
     courseImage:"https://res.cloudinary.com/dxgmovaih/image/upload/v1753360367/woman-buying-tickets-box-office_392895-345595_xoh0rb.jpg",   
     courseTitle:"Ticket Support Executive",
     aboutCourse:"A Passenger Service Associate (PSA) Academy program is a specialized training course created to equip individuals with the essential abilities and understanding necessary for roles in passenger services within the aviation sector. This curriculum addresses a broad spectrum of subjects linked to passenger handling",
     courseRating:4,
     totelRting:"1k + rating",
     totalHurs:"56 + total Hours ",
     Lectures:"67 + ",
     language:"Hindi",
      oldPrice:"31000",
     newPrice:"29500",
    },
]

export default acdemyDat;