const acdemyDat = [
    {
     id:1,
     courseImage:"https://img.freepik.com/premium-photo/stewardess-with-crossed-arms-leaning-her-back-against-turbofan-engine_447912-3940.jpg?w=1380",   
     courseTitle:"Passenger Service Associate",
     aboutCourse:"A Passenger Service Associate (PSA) Academy program is a specialized training course created to equip individuals with the essential abilities and understanding necessary for roles in passenger services within the aviation sector. This curriculum addresses a broad spectrum of subjects linked to passenger handling",
     courseRating:4,
     totelRting:"1k + rating",
     totalHurs:"56 + total Hours ",
     Lectures:"67 + ",
     language:"Hindi",
     oldPrice:"",
     newPrice:" ",
    },
        {
     id:2,
     courseImage:"https://img.freepik.com/premium-photo/stewardess-with-crossed-arms-leaning-her-back-against-turbofan-engine_447912-3940.jpg?w=1380",   
     courseTitle:"Passenger Service Associate",
     aboutCourse:"A Passenger Service Associate (PSA) Academy program is a specialized training course created to equip individuals with the essential abilities and understanding necessary for roles in passenger services within the aviation sector. This curriculum addresses a broad spectrum of subjects linked to passenger handling",
     courseRating:4,
     totelRting:"1k + rating",
     totalHurs:"56 + total Hours ",
     Lectures:"67 + ",
     language:"Hindi",
     oldPrice:"",
     newPrice:" ",
    },
        {
     id:3,
     courseImage:"https://img.freepik.com/premium-photo/stewardess-with-crossed-arms-leaning-her-back-against-turbofan-engine_447912-3940.jpg?w=1380",   
     courseTitle:"Passenger Service Associate",
     aboutCourse:"A Passenger Service Associate (PSA) Academy program is a specialized training course created to equip individuals with the essential abilities and understanding necessary for roles in passenger services within the aviation sector. This curriculum addresses a broad spectrum of subjects linked to passenger handling",
     courseRating:4,
     totelRting:"1k + rating",
     totalHurs:"56 + total Hours ",
     Lectures:"67 + ",
     language:"Hindi",
     oldPrice:"",
     newPrice:" ",
    },
       {
     id:4,
     courseImage:"https://img.freepik.com/premium-photo/stewardess-with-crossed-arms-leaning-her-back-against-turbofan-engine_447912-3940.jpg?w=1380",   
     courseTitle:"Passenger Service Associate",
     aboutCourse:"A Passenger Service Associate (PSA) Academy program is a specialized training course created to equip individuals with the essential abilities and understanding necessary for roles in passenger services within the aviation sector. This curriculum addresses a broad spectrum of subjects linked to passenger handling",
     courseRating:4,
     totelRting:"1k + rating",
     totalHurs:"56 + total Hours ",
     Lectures:"67 + ",
     language:"Hindi",
     oldPrice:"",
     newPrice:" ",
    },
       {
     id:5,
     courseImage:"https://img.freepik.com/premium-photo/stewardess-with-crossed-arms-leaning-her-back-against-turbofan-engine_447912-3940.jpg?w=1380",   
     courseTitle:"Passenger Service Associate",
     aboutCourse:"A Passenger Service Associate (PSA) Academy program is a specialized training course created to equip individuals with the essential abilities and understanding necessary for roles in passenger services within the aviation sector. This curriculum addresses a broad spectrum of subjects linked to passenger handling",
     courseRating:4,
     totelRting:"1k + rating",
     totalHurs:"56 + total Hours ",
     Lectures:"67 + ",
     language:"Hindi",
     oldPrice:"",
     newPrice:" ",
    },
       {
     id:6,
     courseImage:"https://img.freepik.com/premium-photo/stewardess-with-crossed-arms-leaning-her-back-against-turbofan-engine_447912-3940.jpg?w=1380",   
     courseTitle:"Passenger Service Associate",
     aboutCourse:"A Passenger Service Associate (PSA) Academy program is a specialized training course created to equip individuals with the essential abilities and understanding necessary for roles in passenger services within the aviation sector. This curriculum addresses a broad spectrum of subjects linked to passenger handling",
     courseRating:4,
     totelRting:"1k + rating",
     totalHurs:"56 + total Hours ",
     Lectures:"67 + ",
     language:"Hindi",
     oldPrice:"",
     newPrice:" ",
    },
]

export default acdemyDat;